import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate } from '@tanstack/react-router';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, BookOpen, ClipboardList, Layers, Pencil, Plus, Trash2, Upload, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { api, pick, pickList, errorText } from '@/lib/api/client';
import { useAuth } from '@/lib/api/auth';
import { useCourses, useCourse } from '@/lib/api/hooks';
import { fmtDate, inr, paiseToInrInput, submissionState, toCourse, toPaiseExact, type ApiCourse } from '@/lib/api/models';
import { Workspace, PageHeading, Metric, Status, Empty, ErrorBox, Notice, Loading, QueryState } from './shared';
import { ProfilePage } from './student-pages';

const oid = (x: any) => String(x?._id ?? x?.id ?? '');
function useMyCourses() {
  const { user } = useAuth(); const q = useCourses();
  return { ...q, data: q.data?.filter(c => !c.instructorId || c.instructorId === user?.id) };
}
function CoursePicker({ value, onChange }: { value?: string | undefined; onChange: (id: string) => void }) {
  const q = useMyCourses();
  useEffect(() => { if (!value && q.data?.[0]) onChange(q.data[0].id); }, [value, q.data, onChange]);
  return <label className="field max-w-[420px]"><span>Course</span><select value={value ?? ''} onChange={e => onChange(e.target.value)}>{(q.data ?? []).map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></label>;
}

export function InstructorPage({ section = 'overview', courseId }: { section?: string | undefined; courseId?: string | undefined }) {
  if (section === 'profile') return <ProfilePage role="INSTRUCTOR" />;
  return <Workspace role="INSTRUCTOR">{section === 'courses' ? <MyCourses /> : section === 'create' ? <CourseBuilder courseId={courseId} /> : section === 'quizzes' ? <Quizzes initial={courseId} /> : section === 'assignments' ? <Assignments initial={courseId} /> : section === 'submissions' ? <Grading initial={courseId} /> : <Overview />}</Workspace>;
}
function Overview() {
  const q = useMyCourses();
  return <><PageHeading eyebrow="INSTRUCTOR WORKSPACE" title="Teach what you know." description="Build courses, publish assessments, and give meaningful feedback." action={<Button asChild><Link to="/instructor/$section" params={{ section: 'create' }}><Plus />Create course</Link></Button>} />
    <div className="metric-grid"><Metric icon={BookOpen} label="Published courses" value={q.data ? String(q.data.length) : '—'} /><Metric icon={Users} label="Free courses" value={q.data ? String(q.data.filter(c => c.isFree).length) : '—'} /><Metric icon={ClipboardList} label="Paid courses" value={q.data ? String(q.data.filter(c => !c.isFree).length) : '—'} /><Metric icon={Layers} label="Lessons" value={q.data ? String(q.data.reduce((n, c) => n + c.lectureCount, 0)) : '—'} /></div>
    <div className="assessment-grid">{[['quizzes', 'Quiz builder', 'Multiple-choice quizzes with pass marks.'], ['assignments', 'Assignment builder', 'Projects with due dates and marks.'], ['submissions', 'Grading queue', 'Review submissions and give feedback.']].map(([s, t, d]) => <article key={s} className="assessment-card"><h3>{t}</h3><p>{d}</p><Button variant="outline" className="w-full mt-5" asChild><Link to="/instructor/$section" params={{ section: s! }}>Open <ArrowRight /></Link></Button></article>)}</div></>;
}
function MyCourses() {
  const q = useMyCourses(); const qc = useQueryClient(); const [err, setErr] = useState('');
  const del = async (c: ApiCourse) => { if (!confirm(`Delete “${c.title}”? This can’t be undone.`)) return; setErr(''); try { await api(`/instructor/courses/${c.id}`, { method: 'DELETE' }); await qc.invalidateQueries({ queryKey: ['courses'] }); } catch (e) { setErr(errorText(e)); } };
  return <><PageHeading title="My courses" description="Public published courses you teach. Draft courses are not returned by this list." action={<Button asChild><Link to="/instructor/$section" params={{ section: 'create' }}><Plus />New course</Link></Button>} />{err && <ErrorBox message={err} />}
    <QueryState q={q} isEmpty={d => !d?.length} empty={<Empty title="No courses yet" description="Create your first course to start teaching." />}>{d => <div className="table-wrap"><table><thead><tr><th>Course</th><th>Access</th><th>Lessons</th><th>Actions</th></tr></thead><tbody>{d!.map(c => <tr key={c.id}><td><strong>{c.title}</strong><small>{c.category} · {c.level}</small></td><td><Status tone={c.isFree ? 'success' : 'primary'}>{c.isFree ? 'Free' : inr(c.price)}</Status></td><td>{c.lectureCount}</td><td className="flex gap-1"><Button variant="ghost" size="icon" aria-label={`Edit ${c.title}`} asChild><Link to="/instructor/$section" params={{ section: 'create' }} search={{ courseId: c.id }}><Pencil /></Link></Button><Button variant="ghost" size="icon" aria-label={`Delete ${c.title}`} onClick={() => del(c)}><Trash2 /></Button></td></tr>)}</tbody></table></div>}</QueryState></>;
}

function CourseBuilder({ courseId }: { courseId?: string | undefined }) {
  const qc = useQueryClient(); const navigate = useNavigate(); const existing = useCourse(courseId ?? '__none');
  const editing = Boolean(courseId); const c = editing ? existing.data : undefined;
  const [paid, setPaid] = useState(false); const [err, setErr] = useState(''); const [ok, setOk] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { if (c) setPaid(!c.isFree); }, [c]);
  if (editing && existing.isLoading) return <Loading />;
  const save = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault(); const input = new FormData(e.currentTarget); setErr(''); setOk('');
    const price = paid ? toPaiseExact(String(input.get('price') ?? '')) : 0;
    if (!Number.isInteger(price) || (paid && price <= 0)) { setErr('Enter a price in INR with up to two decimal places.'); return; }
    const courseFields = ['title', 'description', 'category', 'accessType', 'price'] as const;
    const f = new FormData();
    for (const field of courseFields) {
      const value = field === 'accessType' ? (paid ? 'PAID' : 'FREE') : field === 'price' ? String(price) : String(input.get(field) ?? '');
      f.set(field, value);
    }
    const thumbnail = input.get('thumbnail'); if (thumbnail instanceof File && thumbnail.size) f.set('thumbnail', thumbnail);
    setBusy(true);
    try { const j = await api(editing ? `/instructor/courses/${courseId}` : '/instructor/courses', { method: editing ? 'PATCH' : 'POST', body: f }); const saved = toCourse(pick(j, 'course')); await qc.invalidateQueries({ queryKey: ['courses'] }); await qc.invalidateQueries({ queryKey: ['course', saved.id || courseId] }); setOk(editing ? 'Course updated.' : 'Course created. Now add your lessons.'); if (!editing && saved.id) navigate({ to: '/instructor/$section', params: { section: 'create' }, search: { courseId: saved.id }, replace: true }); }
    catch (x) { setErr(errorText(x)); } finally { setBusy(false); }
  };
  return <><PageHeading title={editing ? `Edit: ${c?.title ?? 'course'}` : 'Create a course'} description="Course details, access, and recorded lessons." />
    <form className="form-shell" onSubmit={save} key={c?.id ?? 'new'}>{err && <ErrorBox message={err} />}{ok && <Notice tone="success">{ok}</Notice>}
      <label className="field"><span>Title</span><input name="title" required defaultValue={c?.title} /></label><label className="field"><span>Description</span><textarea name="description" rows={4} required defaultValue={c?.description} /></label>
      <label className="field"><span>Category</span><input name="category" required defaultValue={c?.category} placeholder="Development" /></label>
      <label className="field"><span>Thumbnail</span><input name="thumbnail" type="file" accept="image/png,image/jpeg,image/webp" /></label>
      <fieldset className="field"><legend className="text-sm font-semibold mb-2">Access</legend><div className="section-tabs" role="radiogroup"><Button type="button" variant="ghost" role="radio" aria-checked={!paid} className={!paid ? 'selected' : ''} onClick={() => setPaid(false)}>Free</Button><Button type="button" variant="ghost" role="radio" aria-checked={paid} className={paid ? 'selected' : ''} onClick={() => setPaid(true)}>Paid · one-time</Button></div></fieldset>
      {paid && <label className="field max-w-[240px]"><span>Price (INR ₹)</span><input name="price" type="number" min="0.01" step="0.01" required defaultValue={c && !c.isFree ? paiseToInrInput(c.price) : '1499'} /></label>}
      <Button type="submit" disabled={busy}>{busy ? 'Saving…' : editing ? 'Save changes' : 'Create course'}</Button></form>
    {editing && c && <Lectures course={c} />}</>;
}
function Lectures({ course }: { course: ApiCourse }) {
  const qc = useQueryClient(); const [err, setErr] = useState(''); const [busy, setBusy] = useState(false); const [ok, setOk] = useState('');
  const refresh = () => qc.invalidateQueries({ queryKey: ['course', course.id] });
  return <section className="form-shell mt-8"><h2 className="text-lg">Curriculum</h2>{err && <ErrorBox message={err} />}{ok && <Notice tone="success">{ok}</Notice>}
    {course.lectures.length ? <ul className="grid gap-2 mb-6">{course.lectures.map((l, i) => <li key={l.id} className="curriculum-lesson"><span>{i + 1}. {l.title}</span>{l.isPreview && <Status tone="primary">Preview</Status>}<Button variant="ghost" size="icon" aria-label={`Delete ${l.title}`} onClick={async () => { if (!confirm(`Delete lesson “${l.title}”?`)) return; setErr(''); try { await api(`/instructor/courses/${course.id}/lectures/${l.id}`, { method: 'DELETE' }); await refresh(); } catch (x) { setErr(errorText(x)); } }}><Trash2 /></Button></li>)}</ul> : <p className="text-sm text-muted-foreground mb-4">No lessons yet.</p>}
    <form onSubmit={async e => { e.preventDefault(); const form = e.currentTarget; const f = new FormData(form); setErr(''); setOk(''); const v = f.get('video'); if (!(v instanceof File) || !v.size) { setErr('Choose a video file to upload.'); return; } f.set('isPreview', String(f.get('isPreview') === 'on')); setBusy(true); try { await api(`/instructor/courses/${course.id}/lectures`, { body: f }); form.reset(); setOk('Lesson uploaded.'); await refresh(); } catch (x) { setErr(errorText(x)); } finally { setBusy(false); } }}>
      <h3 className="text-base">Add a recorded lesson</h3><label className="field"><span>Lesson title</span><input name="title" required /></label><label className="field"><span>Description</span><textarea name="description" rows={2} /></label><label className="field"><span>Video</span><input name="video" type="file" accept="video/*" required /></label>{!course.isFree && <label className="flex gap-2 text-sm mb-4"><input type="checkbox" name="isPreview" />Make this the public preview lecture</label>}<Button type="submit" disabled={busy}><Upload />{busy ? 'Uploading video…' : 'Upload lesson'}</Button></form></section>;
}

type Q = { question: string; options: string[]; correctOptionIndex: number; explanation: string };
const blankQ = (): Q => ({ question: '', options: ['', '', '', ''], correctOptionIndex: 0, explanation: '' });
function Quizzes({ initial }: { initial?: string | undefined }) {
  const [courseId, setCourseId] = useState(initial); const qc = useQueryClient();
  const list = useQuery({ queryKey: ['instructor-quizzes', courseId], enabled: Boolean(courseId), queryFn: async () => pickList(await api(`/instructor/courses/${courseId}/quizzes`), 'quizzes') });
  const [edit, setEdit] = useState<any | null>(null); const [err, setErr] = useState('');
  const refresh = () => qc.invalidateQueries({ queryKey: ['instructor-quizzes', courseId] });
  return <><PageHeading title="Quizzes" description="Multiple-choice quizzes. Students see correct answers only after submitting." action={<Button onClick={() => setEdit({ title: '', passMark: 80, status: 'DRAFT', questions: [blankQ()] })} disabled={!courseId}><Plus />New quiz</Button>} /><CoursePicker value={courseId} onChange={setCourseId} />{err && <ErrorBox message={err} />}
    {edit ? <QuizEditor courseId={courseId!} quiz={edit} onDone={() => { setEdit(null); void refresh(); }} /> : <QueryState q={list} isEmpty={d => !d.length} empty={<Empty title="No quizzes yet" description="Create a quiz for this course." />}>{d => <div className="table-wrap"><table><thead><tr><th>Quiz</th><th>Status</th><th>Pass mark</th><th>Actions</th></tr></thead><tbody>{d.map((z: any) => <tr key={oid(z)}><td><strong>{z.title}</strong><small>{z.questions?.length ?? 0} questions</small></td><td><Status tone={String(z.status).toUpperCase() === 'PUBLISHED' ? 'success' : 'warning'}>{String(z.status ?? 'DRAFT').toLowerCase()}</Status></td><td>{z.passMark ?? 80}%</td><td className="flex gap-1"><Button variant="ghost" size="icon" aria-label="Edit quiz" onClick={() => setEdit(z)}><Pencil /></Button><Button variant="ghost" size="icon" aria-label="Delete quiz" onClick={async () => { if (!confirm('Delete this quiz?')) return; setErr(''); try { await api(`/instructor/courses/${courseId}/quizzes/${oid(z)}`, { method: 'DELETE' }); void refresh(); } catch (x) { setErr(errorText(x)); } }}><Trash2 /></Button></td></tr>)}</tbody></table></div>}</QueryState>}</>;
}
function QuizEditor({ courseId, quiz, onDone }: { courseId: string; quiz: any; onDone: () => void }) {
  const [title, setTitle] = useState(quiz.title ?? ''); const [pass, setPass] = useState(Number(quiz.passMark ?? 80)); const [status, setStatus] = useState(String(quiz.status ?? 'DRAFT').toUpperCase());
  const [qs, setQs] = useState<Q[]>((quiz.questions ?? []).map((q: any) => ({ question: q.prompt ?? q.question ?? q.text ?? '', options: q.options ?? ['', ''], correctOptionIndex: Number(q.correctOptionIndex ?? q.correctAnswer ?? 0), explanation: q.explanation ?? '' })));
  const [err, setErr] = useState(''); const [busy, setBusy] = useState(false); const up = (i: number, p: Partial<Q>) => setQs(s => s.map((q, n) => (n === i ? { ...q, ...p } : q)));
  return <form className="form-shell mt-4" onSubmit={async e => { e.preventDefault(); setErr(''); if (qs.some(q => !q.question.trim() || q.options.filter(o => o.trim()).length < 2)) { setErr('Every question needs text and at least two options.'); return; } setBusy(true); try { const body = { title, passMark: pass, status, questions: qs.map(q => ({ prompt: q.question, options: q.options.filter(o => o.trim()), correctOptionIndex: q.correctOptionIndex, explanation: q.explanation })) }; await api(oid(quiz) ? `/instructor/courses/${courseId}/quizzes/${oid(quiz)}` : `/instructor/courses/${courseId}/quizzes`, { method: oid(quiz) ? 'PATCH' : 'POST', body }); onDone(); } catch (x) { setErr(errorText(x)); } finally { setBusy(false); } }}>
    {err && <ErrorBox message={err} />}<div className="form-grid"><label className="field"><span>Quiz title</span><input value={title} onChange={e => setTitle(e.target.value)} required /></label><label className="field"><span>Pass mark (%)</span><input type="number" min={1} max={100} value={pass} onChange={e => setPass(Number(e.target.value))} /></label></div>
    <label className="field max-w-[240px]"><span>Status</span><select value={status} onChange={e => setStatus(e.target.value)}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></select></label>
    {qs.map((q, i) => <fieldset key={i} className="summary-block mb-4"><legend className="font-semibold text-sm">Question {i + 1}</legend><label className="field"><span>Question</span><input value={q.question} onChange={e => up(i, { question: e.target.value })} /></label>{q.options.map((o, k) => <label key={k} className="flex gap-2 items-center mb-2"><input type="radio" name={`c${i}`} checked={q.correctOptionIndex === k} onChange={() => up(i, { correctOptionIndex: k })} aria-label={`Mark option ${k + 1} correct`} /><input className="flex-1 border rounded-md px-3 py-2 text-sm bg-background" value={o} placeholder={`Option ${k + 1}`} onChange={e => up(i, { options: q.options.map((x, n) => (n === k ? e.target.value : x)) })} /></label>)}<label className="field"><span>Explanation (shown after submission)</span><input value={q.explanation} onChange={e => up(i, { explanation: e.target.value })} /></label>{qs.length > 1 && <Button type="button" variant="ghost" size="sm" onClick={() => setQs(s => s.filter((_, n) => n !== i))}><Trash2 />Remove question</Button>}</fieldset>)}
    <div className="flex gap-2"><Button type="button" variant="outline" onClick={() => setQs(s => [...s, blankQ()])}><Plus />Add question</Button><Button type="submit" disabled={busy}>{busy ? 'Saving…' : 'Save quiz'}</Button><Button type="button" variant="ghost" onClick={onDone}>Cancel</Button></div></form>;
}
function Assignments({ initial }: { initial?: string | undefined }) {
  const [courseId, setCourseId] = useState(initial); const qc = useQueryClient();
  const list = useQuery({ queryKey: ['instructor-assignments', courseId], enabled: Boolean(courseId), queryFn: async () => pickList(await api(`/instructor/courses/${courseId}/assignments`), 'assignments') });
  const [edit, setEdit] = useState<any | null>(null); const [err, setErr] = useState(''); const [busy, setBusy] = useState(false);
  const refresh = () => qc.invalidateQueries({ queryKey: ['instructor-assignments', courseId] });
  return <><PageHeading title="Assignments" description="Projects with instructions, due dates, and maximum marks." action={<Button onClick={() => setEdit({})} disabled={!courseId}><Plus />New assignment</Button>} /><CoursePicker value={courseId} onChange={setCourseId} />{err && <ErrorBox message={err} />}
    {edit ? <form className="form-shell mt-4" onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); setErr(''); setBusy(true); const dueDate = String(f.get('dueDate') ?? ''); const content = { title: String(f.get('title') ?? ''), instructions: String(f.get('instructions') ?? ''), dueDate: dueDate ? new Date(dueDate).toISOString() : undefined, maxMarks: Number(f.get('maxMarks')) }; const status = String(f.get('status')); const currentStatus = String(edit.status ?? 'DRAFT').toUpperCase(); const assignmentPath = `/instructor/courses/${courseId}/assignments`; let assignmentId = oid(edit); const contentChanged = !assignmentId || content.title !== String(edit.title ?? '') || content.instructions !== String(edit.instructions ?? '') || dueDate !== (edit.dueDate ? String(edit.dueDate).slice(0, 10) : '') || content.maxMarks !== Number(edit.maxMarks ?? 100); try { if (!assignmentId || contentChanged) { const result = await api<any>(assignmentId ? `${assignmentPath}/${assignmentId}` : assignmentPath, { method: assignmentId ? 'PATCH' : 'POST', body: content }); assignmentId ||= oid(pick(result, 'assignment')); } if (status !== currentStatus && assignmentId) await api(`${assignmentPath}/${assignmentId}`, { method: 'PATCH', body: { status } }); setEdit(null); void refresh(); } catch (x) { setErr(errorText(x)); } finally { setBusy(false); } }}>
      <label className="field"><span>Title</span><input name="title" required defaultValue={edit.title} /></label><label className="field"><span>Instructions</span><textarea name="instructions" rows={5} required defaultValue={edit.instructions} /></label><div className="form-grid"><label className="field"><span>Due date</span><input name="dueDate" type="date" defaultValue={edit.dueDate ? String(edit.dueDate).slice(0, 10) : ''} /></label><label className="field"><span>Maximum marks</span><input name="maxMarks" type="number" min={1} required defaultValue={edit.maxMarks ?? 100} /></label></div><label className="field max-w-[240px]"><span>Status</span><select name="status" defaultValue={String(edit.status ?? 'DRAFT').toUpperCase()}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></select></label><div className="flex gap-2"><Button type="submit" disabled={busy}>{busy ? 'Saving…' : 'Save assignment'}</Button><Button type="button" variant="ghost" onClick={() => setEdit(null)}>Cancel</Button></div></form>
      : <QueryState q={list} isEmpty={d => !d.length} empty={<Empty title="No assignments yet" description="Create an assignment for this course." />}>{d => <div className="table-wrap"><table><thead><tr><th>Assignment</th><th>Status</th><th>Due</th><th>Actions</th></tr></thead><tbody>{d.map((a: any) => <tr key={oid(a)}><td><strong>{a.title}</strong><small>{a.maxMarks ?? 100} marks</small></td><td><Status tone={String(a.status).toUpperCase() === 'PUBLISHED' ? 'success' : 'warning'}>{String(a.status ?? 'DRAFT').toLowerCase()}</Status></td><td>{fmtDate(a.dueDate)}</td><td className="flex gap-1"><Button variant="ghost" size="icon" aria-label="Edit assignment" onClick={() => setEdit(a)}><Pencil /></Button><Button variant="ghost" size="sm" asChild><Link to="/instructor/$section" params={{ section: 'submissions' }} search={courseId ? { courseId } : {}}>Submissions</Link></Button><Button variant="ghost" size="icon" aria-label="Delete assignment" onClick={async () => { if (!confirm('Delete this assignment?')) return; setErr(''); try { await api(`/instructor/courses/${courseId}/assignments/${oid(a)}`, { method: 'DELETE' }); void refresh(); } catch (x) { setErr(errorText(x)); } }}><Trash2 /></Button></td></tr>)}</tbody></table></div>}</QueryState>}</>;
}
function Grading({ initial }: { initial?: string | undefined }) {
  const [courseId, setCourseId] = useState(initial); const [assignmentId, setAssignmentId] = useState<string>();
  const as = useQuery({ queryKey: ['instructor-assignments', courseId], enabled: Boolean(courseId), queryFn: async () => pickList(await api(`/instructor/courses/${courseId}/assignments`), 'assignments') });
  useEffect(() => { setAssignmentId(as.data?.[0] ? oid(as.data[0]) : undefined); }, [as.data]);
  const subs = useQuery({ queryKey: ['instructor-subs', courseId, assignmentId], enabled: Boolean(courseId && assignmentId), queryFn: async () => pickList(await api(`/instructor/courses/${courseId}/assignments/${assignmentId}/submissions`), 'submissions') });
  const max = as.data?.find((a: any) => oid(a) === assignmentId)?.maxMarks ?? 100;
  return <><PageHeading title="Grading queue" description="Review student work, give marks and feedback, or request a resubmission." /><div className="form-grid"><CoursePicker value={courseId} onChange={setCourseId} /><label className="field"><span>Assignment</span><select value={assignmentId ?? ''} onChange={e => setAssignmentId(e.target.value)}>{(as.data ?? []).map((a: any) => <option key={oid(a)} value={oid(a)}>{a.title}</option>)}</select></label></div>
    {!assignmentId ? <Empty title="No assignments" description="Create an assignment to start receiving submissions." /> : <QueryState q={subs} isEmpty={d => !d.length} empty={<Empty title="No submissions yet" description="Student submissions will appear here." />}>{d => <div className="grid gap-4">{d.map((s: any) => <ReviewCard key={oid(s)} s={s} max={max} path={`/instructor/courses/${courseId}/assignments/${assignmentId}/submissions/${oid(s)}/review`} onSaved={() => subs.refetch()} />)}</div>}</QueryState>}</>;
}
function ReviewCard({ s, max, path, onSaved }: { s: any; max: number; path: string; onSaved: () => void }) {
  const [marks, setMarks] = useState(s.marks ?? ''); const [feedback, setFeedback] = useState(s.feedback ?? ''); const [err, setErr] = useState(''); const [busy, setBusy] = useState(false);
  const st = submissionState(s); const file = typeof s.file === 'string' ? s.file : s.file?.url ?? s.fileUrl;
  const send = async (status: 'GRADED' | 'RESUBMISSION_REQUESTED') => { setErr(''); if (status === 'GRADED' && (marks === '' || Number(marks) < 0 || Number(marks) > max)) { setErr(`Enter marks between 0 and ${max}.`); return; } if (status === 'RESUBMISSION_REQUESTED' && !String(feedback).trim()) { setErr('Add feedback explaining what to change.'); return; } if (status === 'GRADED' && !String(feedback).trim()) { setErr('Add feedback with the grade.'); return; } setBusy(true); try { const body = status === 'GRADED' ? { action: 'GRADE', marks: Number(marks), feedback } : { action: 'REQUEST_RESUBMISSION', feedback }; await api(path, { method: 'PATCH', body }); onSaved(); } catch (x) { setErr(errorText(x)); } finally { setBusy(false); } };
  return <article className="summary-block"><div className="flex justify-between flex-wrap gap-2"><div><h3 className="m-0">{s.student?.name ?? s.user?.name ?? 'Student'}</h3><p className="text-xs text-muted-foreground">Version {s.version ?? 1} · {fmtDate(s.createdAt ?? s.submittedAt)}{(s.isLate || s.late) ? ' · Late' : ''}</p></div><Status tone={st === 'GRADED' ? 'success' : st === 'RESUBMISSION_REQUESTED' ? 'danger' : 'warning'}>{st.replace(/_/g, ' ').toLowerCase()}</Status></div>
    {s.answer && <p className="text-sm whitespace-pre-line">{s.answer}</p>}<div className="flex gap-3 text-sm">{s.projectUrl && <a className="text-primary" href={s.projectUrl} target="_blank" rel="noreferrer">Project link</a>}{file && <a className="text-primary" href={file} target="_blank" rel="noreferrer">Download file</a>}</div>
    {err && <ErrorBox message={err} />}<div className="form-grid mt-3"><label className="field"><span>Marks (out of {max})</span><input type="number" min={0} max={max} value={marks} onChange={e => setMarks(e.target.value)} /></label><label className="field"><span>Feedback</span><textarea rows={2} value={feedback} onChange={e => setFeedback(e.target.value)} /></label></div>
    <div className="flex gap-2"><Button onClick={() => send('GRADED')} disabled={busy}>Grade</Button><Button variant="outline" onClick={() => send('RESUBMISSION_REQUESTED')} disabled={busy}>Request resubmission</Button></div></article>;
}
