import { useMemo, useState } from 'react';
import { Link, useNavigate } from '@tanstack/react-router';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, ArrowUpRight, Award, BookOpen, Check, CheckCircle2, ChevronRight, Clock3, Code2, GraduationCap, LockKeyhole, Play, Search, ShieldCheck, SlidersHorizontal, Sparkles, Video, Infinity as InfinityIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Header, Footer, CourseCard, PageHeading, Status, Empty, QueryState, ErrorBox, Notice, Loading } from './shared';
import { api, pick, errorText, errorStatus } from '@/lib/api/client';
import { useAuth } from '@/lib/api/auth';
import { useCourses, useCourse, useMyLearning, useCheckout } from '@/lib/api/hooks';
import { inr, toLecture, toPaise, type ApiCourse } from '@/lib/api/models';
import studio from '@/assets/learning-studio.jpg';

export function HomePage() {
  const [search, setSearch] = useState(''); const [category, setCategory] = useState('All courses'); const navigate = useNavigate();
  const q = useCourses();
  const cats = useMemo(() => ['All courses', ...Array.from(new Set((q.data ?? []).map(c => c.category)))], [q.data]);
  return <><Header /><main><section className="home-hero"><img src={studio} alt="A learner building career skills in a bright creative studio" className="hero-photo" width={1536} height={1024} /><div className="hero-shade" /><div className="wide hero-content"><div className="hero-eyebrow"><span /> YOUR AMBITION. YOUR PACE.</div><h1>Learn skills that move<br />your career <span className="hero-accent">forward.</span></h1><p className="hero-copy">Expert-led courses. Hands-on learning. Real-world skills.<br />Invest in yourself and build a future you’re proud of.</p><form className="hero-search" onSubmit={e => { e.preventDefault(); navigate({ to: '/courses', search: { q: search } }); }}><Search size={18} /><input aria-label="Search courses" value={search} onChange={e => setSearch(e.target.value)} placeholder="What do you want to learn?" /><Button type="submit">Find your course <ArrowRight size={15} /></Button></form></div><div className="hero-floating"><span className="badge-icon"><Award size={23} /></span><div><strong>Your effort. Recognized.</strong><p>Earn a certificate. Showcase your skills.</p></div><CheckCircle2 size={17} className="text-success" /></div></section>
    <section className="trust-band"><div className="wide trust-inner">{[[BookOpen, q.data ? String(q.data.length) : '—', 'Published courses'], [Sparkles, q.data ? String(q.data.filter(c => c.isFree).length) : '—', 'Completely free courses'], [GraduationCap, q.data ? String(new Set(q.data.map(c => c.instructorName)).size) : '—', 'Instructors'], [Award, 'Verified', 'Certificates earned by assessment']].map(([Icon, value, label]) => { const I = Icon as typeof BookOpen; return <div className="trust-item" key={String(label)}><I /><div><strong>{String(value)}</strong><p>{String(label)}</p></div></div>; })}</div></section>
    <section className="wide home-section"><div className="section-heading"><div><div className="eyebrow">INVEST IN YOUR NEXT CHAPTER</div><h2>Skills worth learning.</h2><p>Practical, thoughtfully crafted courses. Taught by people who do.</p></div><Link to="/courses">View all courses <ArrowUpRight size={15} /></Link></div><div className="category-row">{cats.map(cat => <Button key={cat} variant="outline" className={`category-chip ${category === cat ? 'active' : ''}`} onClick={() => setCategory(cat)}>{cat}</Button>)}</div>
      <QueryState q={q} rows={2} isEmpty={d => !d.some(c => !c.isFree)} empty={<Empty title="Paid courses are on the way" description="Start with a free course in the meantime." />}>{d => <div className="course-grid">{d.filter(c => !c.isFree && (category === 'All courses' || c.category === category)).slice(0, 6).map(c => <CourseCard course={c} key={c.id} />)}</div>}</QueryState></section>
    <section className="wide home-section free-section"><div className="section-heading"><div><div className="free-kicker"><Sparkles size={13} /> A LITTLE CURIOSITY GOES A LONG WAY</div><h2>Learn for free.</h2><p>Your first step shouldn’t come with a price tag. Start here.</p></div><Link to="/courses" search={{ free: true }}>Explore free courses <ArrowUpRight size={15} /></Link></div><QueryState q={q} rows={1} isEmpty={d => !d.some(c => c.isFree)} empty={<Empty title="Free courses coming soon" description="Check back shortly." />}>{d => <div className="course-grid">{d.filter(c => c.isFree).slice(0, 6).map(c => <CourseCard key={c.id} course={c} />)}</div>}</QueryState></section>
    <section className="value-band"><div className="wide value-grid">{[[Clock3, 'Learning on your terms', 'Lifetime access. No schedules. Make progress at your own pace.'], [Code2, 'Skills you can actually use', 'Build real projects and turn your knowledge into confidence.'], [ShieldCheck, 'Achievement that means something', 'Earn verified certificates through learning and assessment.']].map(([Icon, title, copy]) => { const I = Icon as typeof Clock3; return <div className="value-item" key={String(title)}><I size={24} /><div><h3>{String(title)}</h3><p>{String(copy)}</p></div></div>; })}</div></section>
    <section className="instructor-band"><div className="wide instructor-inner"><div><div className="eyebrow">KNOWLEDGE IS BETTER SHARED</div><h2>Someone’s next chapter starts with you.</h2><p>Instructor accounts are granted by a SkillForge administrator.</p></div><Button asChild><a href="mailto:help@skillforge.example?subject=Become%20an%20instructor">Become an instructor <ArrowUpRight /></a></Button></div></section></main><Footer /></>;
}

export function CatalogPage({ q = '', free = false }: { q?: string | undefined; free?: boolean | undefined }) {
  const courses = useCourses();
  const [search, setSearch] = useState(q); const [category, setCategory] = useState('All'); const [level, setLevel] = useState('All levels'); const [access, setAccess] = useState(free ? 'Free' : 'All'); const [price, setPrice] = useState(toPaise(5000)); const [sort, setSort] = useState('Newest'); const [filters, setFilters] = useState(false);
  const all = courses.data ?? [];
  const cats = ['All', ...Array.from(new Set(all.map(c => c.category)))]; const levels = ['All levels', ...Array.from(new Set(all.map(c => c.level)))];
  const maxPrice = Math.max(toPaise(5000), ...all.map(c => c.price));
  let filtered = all.filter(c => (!search || `${c.title} ${c.instructorName} ${c.category}`.toLowerCase().includes(search.toLowerCase())) && (category === 'All' || c.category === category) && (level === 'All levels' || c.level === level) && (access === 'All' || (access === 'Free' ? c.isFree : !c.isFree)) && (c.isFree || c.price <= price));
  if (sort === 'Price: low to high') filtered = [...filtered].sort((a, b) => a.price - b.price);
  if (sort === 'Highest rated') filtered = [...filtered].sort((a, b) => (b.rating ?? 0) - (a.rating ?? 0));
  const reset = () => { setSearch(''); setCategory('All'); setLevel('All levels'); setAccess('All'); setPrice(maxPrice); };
  return <><Header /><main className="wide public-page"><PageHeading eyebrow="A NEW SKILL. A NEW POSSIBILITY." title={access === 'Free' ? 'Learn without limits. For free.' : 'Find your next chapter.'} description="Explore practical courses built for real-world progress." /><div className="catalog-layout"><aside className={`filter-sidebar ${filters ? 'filters-open' : ''}`}><div className="flex justify-between"><h3>Filters</h3><Button variant="link" size="sm" onClick={reset}>Reset</Button></div>
    <fieldset className="filter-group"><legend>Category</legend>{cats.map(c => <label key={c}><input type="radio" name="category" checked={c === category} onChange={() => setCategory(c)} />{c}</label>)}</fieldset>
    <fieldset className="filter-group"><legend>Level</legend>{levels.map(l => <label key={l}><input type="radio" name="level" checked={l === level} onChange={() => setLevel(l)} />{l}</label>)}</fieldset>
    <fieldset className="filter-group"><legend>Course access</legend>{['All', 'Free', 'Paid'].map(a => <label key={a}><input type="radio" name="access" checked={a === access} onChange={() => setAccess(a)} />{a}</label>)}</fieldset>
    <fieldset className="filter-group"><legend>Maximum price · {inr(price)}</legend><input className="w-full accent-primary" type="range" min="0" max={maxPrice} step={toPaise(100)} aria-label="Maximum price" value={price} onChange={e => setPrice(Number(e.target.value))} /></fieldset></aside>
    <div><div className="catalog-top"><div className="search-field"><Search size={17} /><input aria-label="Search catalogue" placeholder="Search courses or instructors…" value={search} onChange={e => setSearch(e.target.value)} /></div><Button variant="outline" className="filter-toggle" onClick={() => setFilters(!filters)}><SlidersHorizontal />Filters</Button><select aria-label="Sort courses" className="field-select" value={sort} onChange={e => setSort(e.target.value)}>{['Newest', 'Highest rated', 'Price: low to high'].map(s => <option key={s}>{s}</option>)}</select></div>
      <QueryState q={courses} isEmpty={d => d.length === 0} empty={<Empty title="No courses published yet" description="New courses are on the way. Check back soon." />}>{() => <><p className="results-count">{filtered.length} courses to move you forward</p><div className="course-grid">{filtered.map(c => <CourseCard key={c.id} course={c} />)}</div>{!filtered.length && <Empty title="No courses found" description="Try a different search or broaden your filters." action={<Button onClick={reset}>Clear filters</Button>} />}</>}</QueryState></div></div></main><Footer /></>;
}

function PreviewDialog({ course, open, onClose }: { course: ApiCourse; open: boolean; onClose: () => void }) {
  const q = useQuery({ queryKey: ['preview', course.id], enabled: open, retry: false, queryFn: async () => toLecture(pick(await api(`/courses/${course.id}/preview`), 'lecture', 'preview')) });
  return <Dialog open={open} onOpenChange={v => !v && onClose()}><DialogContent className="preview-dialog"><DialogTitle>{course.title}</DialogTitle><DialogDescription>{q.data ? `Public preview · ${q.data.title}` : 'Public preview lecture'}</DialogDescription>
    {q.isLoading ? <div className="preview-video bg-muted animate-pulse" /> : q.error ? <ErrorBox message={errorStatus(q.error) === 404 ? 'This course doesn’t have a public preview yet.' : errorText(q.error)} /> : q.data?.videoUrl ? <video controls autoPlay poster={course.thumbnail} className="preview-video" src={q.data.videoUrl} aria-label="Public preview lecture" /> : <Empty title="Preview unavailable" description="The instructor hasn’t added a preview video yet." />}
    <Status tone="primary">Free preview · No sign-in needed</Status></DialogContent></Dialog>;
}

export function CourseDetailPage({ id, openPreview = false }: { id: string; openPreview?: boolean | undefined }) {
  const q = useCourse(id); const { user, status } = useAuth(); const learning = useMyLearning(); const qc = useQueryClient(); const navigate = useNavigate();
  const [preview, setPreview] = useState(openPreview); const [enrollErr, setEnrollErr] = useState(''); const [enrolling, setEnrolling] = useState(false);
  const checkout = useCheckout(q.data, user ? { name: user.name, email: user.email } : undefined);
  if (q.isLoading) return <><Header /><main className="wide public-page"><Loading rows={3} /></main><Footer /></>;
  if (q.error || !q.data) return <><Header /><main className="wide public-page"><Empty title={errorStatus(q.error) === 404 ? 'Course not found' : 'We couldn’t load this course'} description={q.error ? errorText(q.error) : 'Discover another learning opportunity.'} action={<Button asChild><Link to="/courses">Explore courses</Link></Button>} /></main><Footer /></>;
  const course = q.data;
  const owned = Boolean(course.hasAccess || course.isEnrolled || course.isPurchased || learning.data?.some(l => l.course.id === course.id));
  const stateLabel = status !== 'authenticated' ? 'Visitor' : user?.role !== 'STUDENT' ? `${user?.role.toLowerCase()} view` : owned ? (course.isFree ? 'Enrolled' : 'Purchased') : 'No access yet';
  const act = async () => {
    if (status !== 'authenticated') { navigate({ to: '/login', search: { redirect: `/courses/${id}` } }); return; }
    if (user?.role !== 'STUDENT') return;
    if (owned) { navigate({ to: '/learn/$courseId', params: { courseId: id } }); return; }
    if (course.isFree) { setEnrolling(true); setEnrollErr(''); try { await api(`/courses/${id}/enroll`, { method: 'POST' }); await qc.invalidateQueries({ queryKey: ['me', 'learning'] }); navigate({ to: '/learn/$courseId', params: { courseId: id } }); } catch (e) { if (errorStatus(e) === 409) { await qc.invalidateQueries({ queryKey: ['me', 'learning'] }); navigate({ to: '/learn/$courseId', params: { courseId: id } }); } else setEnrollErr(errorText(e)); } finally { setEnrolling(false); } return; }
    void checkout.start();
  };
  const ph = checkout.state.phase; const busy = enrolling || ph === 'creating' || ph === 'verifying' || ph === 'awaiting' || learning.isLoading;
  const label = user && user.role !== 'STUDENT' ? 'Student accounts can enroll' : status !== 'authenticated' ? (course.isFree ? 'Sign in to enroll free' : `Sign in to buy — ${inr(course.price)}`) : ph === 'creating' ? 'Preparing secure checkout…' : ph === 'verifying' ? 'Verifying payment…' : enrolling ? 'Enrolling…' : owned ? 'Continue Learning' : course.isFree ? 'Enroll Free' : `Buy Course — ${inr(course.price)}`;
  return <><Header /><main><section className="detail-band"><div className="wide detail-inner"><div><Link to="/courses" className="flex gap-2 items-center text-xs mb-5">Courses <ChevronRight size={12} />{course.category}</Link><div className="flex gap-2 flex-wrap"><Status tone="primary">{course.level} · Self-paced</Status><Status tone={owned ? 'success' : 'neutral'}>{stateLabel}</Status></div><h1>{course.title}</h1><p>{course.description}</p><div className="detail-meta">{course.rating != null && <span className="rating">★ {course.rating}</span>}<span>{course.lectureCount} lessons</span><span>{course.category}</span></div><p className="mt-5 mb-0">Created by <strong className="text-primary-foreground">{course.instructorName}</strong></p></div><div className="detail-preview"><img src={course.thumbnail ?? studio} alt={course.title} width={1024} height={640} /><Button aria-label="Watch public preview" onClick={() => setPreview(true)}><Play />Watch the free preview</Button></div></div></section>
    <div className="wide detail-content"><div>{course.outcomes.length > 0 && <section className="content-block"><h2>What you’ll learn</h2><div className="learn-list">{course.outcomes.map(s => <div key={s}><Check />{s}</div>)}</div></section>}
      <section className="content-block"><div className="flex justify-between"><h2>Course curriculum</h2><span className="text-xs text-muted-foreground">{course.lectureCount} lessons</span></div><div className="curriculum"><details open><summary>Lessons</summary>{course.lectures.length === 0 && <p className="text-sm text-muted-foreground p-4">The curriculum is being prepared.</p>}{[...course.lectures].sort((a, b) => a.order - b.order).map(l => { const isPrev = l.isPreview || l.id === course.previewLectureId; return <div className="curriculum-lesson" key={l.id}>{owned || isPrev ? <Play size={14} /> : <LockKeyhole size={14} aria-label="Locked" />}<span>{l.title}</span>{l.duration ? <small className="text-muted-foreground">{Math.round(l.duration / 60)} min</small> : <small />}{isPrev ? <Button variant="link" size="sm" onClick={() => setPreview(true)}>Preview</Button> : owned ? <Button variant="link" size="sm" asChild><Link to="/learn/$courseId" params={{ courseId: id }} search={{ lecture: l.id }}>Watch</Link></Button> : <small className="text-muted-foreground">Locked</small>}</div>; })}</details></div></section>
      <section className="content-block"><h2>Requirements</h2>{course.requirements.length ? <ul className="text-sm text-muted-foreground list-disc pl-5">{course.requirements.map(r => <li key={r}>{r}</li>)}</ul> : <p className="text-sm text-muted-foreground">A laptop, an internet connection, and a willingness to practice.</p>}</section>
      <section className="content-block"><h2>Meet your instructor</h2><p className="text-sm text-muted-foreground"><strong>{course.instructorName}</strong> · SkillForge instructor</p></section>
      <h2 className="text-xl">Your course outcome</h2><p className="text-sm text-muted-foreground">Skills you can put to work, and a certificate earned through lecture completion and assessments.</p></div>
      <aside className="purchase-panel"><h2 className={course.isFree ? 'text-success' : ''}>{course.isFree ? 'Free' : inr(course.price)}</h2><p>{course.isFree ? 'Completely free. No payment required.' : 'Individual one-time purchase. No subscription.'}</p>
        {ph === 'success' ? <Notice tone="success"><strong>Purchase successful.</strong> Your payment was verified and the course is now in My Learning.</Notice> : ph === 'owned' ? <Notice tone="success">{checkout.state.message}</Notice> : (ph === 'cancelled' || ph === 'failed') ? <Notice tone={ph === 'failed' ? 'danger' : 'warning'}>{checkout.state.message}</Notice> : ph === 'awaiting' ? <Notice tone="warning">Complete payment in the Razorpay window. Access is granted only after we verify it.</Notice> : null}
        {enrollErr && <ErrorBox message={enrollErr} />}
        <Button onClick={act} disabled={busy || (user != null && user.role !== 'STUDENT')} className="w-full">{ph === 'success' || ph === 'owned' ? 'Start learning' : label}<ArrowRight /></Button>
        {!course.isFree && <p className="text-[11px] text-muted-foreground mt-2 text-center">Razorpay Test Mode · No real money is charged</p>}
        <ul>{[[Video, `${course.lectureCount} recorded lessons`], [InfinityIcon, 'Lifetime course access'], [BookOpen, 'Quizzes & instructor feedback'], [Award, 'Certificate of achievement']].map(([Icon, text]) => { const I = Icon as typeof Video; return <li key={String(text)}><I />{String(text)}</li>; })}</ul></aside></div></main>
    <PreviewDialog course={course} open={preview} onClose={() => setPreview(false)} /><Footer /></>;
}
