/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RestrictedRouteImport } from './routes/restricted'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSectionRouteImport } from './routes/admin.$section'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as InstructorIndexRouteImport } from './routes/instructor.index'
import { Route as InstructorSectionRouteImport } from './routes/instructor.$section'
import { Route as LearnCourseIdRouteImport } from './routes/learn.$courseId'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as RestPasswordTokenRouteImport } from './routes/rest-password.$token'
import { Route as StudentSectionRouteImport } from './routes/student.$section'
import { Route as VerifyIndexRouteImport } from './routes/verify.index'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as AssignmentsCourseIdAssignmentIdRouteImport } from './routes/assignments.$courseId.$assignmentId'
import { Route as QuizzesCourseIdQuizIdRouteImport } from './routes/quizzes.$courseId.$quizId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RestrictedRoute = RestrictedRouteImport.update({
  id: '/restricted',
  path: '/restricted',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/admin/$section',
  path: '/admin/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const InstructorIndexRoute = InstructorIndexRouteImport.update({
  id: '/instructor/',
  path: '/instructor/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorSectionRoute = InstructorSectionRouteImport.update({
  id: '/instructor/$section',
  path: '/instructor/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseIdRoute = LearnCourseIdRouteImport.update({
  id: '/learn/$courseId',
  path: '/learn/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RestPasswordTokenRoute = RestPasswordTokenRouteImport.update({
  id: '/rest-password/$token',
  path: '/rest-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSectionRoute = StudentSectionRouteImport.update({
  id: '/student/$section',
  path: '/student/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsCourseIdAssignmentIdRoute =
  AssignmentsCourseIdAssignmentIdRouteImport.update({
    id: '/assignments/$courseId/$assignmentId',
    path: '/assignments/$courseId/$assignmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const QuizzesCourseIdQuizIdRoute = QuizzesCourseIdQuizIdRouteImport.update({
  id: '/quizzes/$courseId/$quizId',
  path: '/quizzes/$courseId/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/restricted': typeof RestrictedRoute
  '/admin/$section': typeof AdminSectionRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructor/$section': typeof InstructorSectionRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/rest-password/$token': typeof RestPasswordTokenRoute
  '/student/$section': typeof StudentSectionRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/assignments/$courseId/$assignmentId': typeof AssignmentsCourseIdAssignmentIdRoute
  '/quizzes/$courseId/$quizId': typeof QuizzesCourseIdQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/restricted': typeof RestrictedRoute
  '/admin/$section': typeof AdminSectionRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructor/$section': typeof InstructorSectionRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/rest-password/$token': typeof RestPasswordTokenRoute
  '/student/$section': typeof StudentSectionRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/instructor': typeof InstructorIndexRoute
  '/verify': typeof VerifyIndexRoute
  '/assignments/$courseId/$assignmentId': typeof AssignmentsCourseIdAssignmentIdRoute
  '/quizzes/$courseId/$quizId': typeof QuizzesCourseIdQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/restricted': typeof RestrictedRoute
  '/admin/$section': typeof AdminSectionRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructor/$section': typeof InstructorSectionRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/rest-password/$token': typeof RestPasswordTokenRoute
  '/student/$section': typeof StudentSectionRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/assignments/$courseId/$assignmentId': typeof AssignmentsCourseIdAssignmentIdRoute
  '/quizzes/$courseId/$quizId': typeof QuizzesCourseIdQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/restricted'
    | '/admin/$section'
    | '/courses/$courseId'
    | '/instructor/$section'
    | '/learn/$courseId'
    | '/reset-password/$token'
    | '/rest-password/$token'
    | '/student/$section'
    | '/verify/$id'
    | '/admin/'
    | '/courses/'
    | '/instructor/'
    | '/verify/'
    | '/assignments/$courseId/$assignmentId'
    | '/quizzes/$courseId/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/restricted'
    | '/admin/$section'
    | '/courses/$courseId'
    | '/instructor/$section'
    | '/learn/$courseId'
    | '/reset-password/$token'
    | '/rest-password/$token'
    | '/student/$section'
    | '/verify/$id'
    | '/admin'
    | '/courses'
    | '/instructor'
    | '/verify'
    | '/assignments/$courseId/$assignmentId'
    | '/quizzes/$courseId/$quizId'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/restricted'
    | '/admin/$section'
    | '/courses/$courseId'
    | '/instructor/$section'
    | '/learn/$courseId'
    | '/reset-password/$token'
    | '/rest-password/$token'
    | '/student/$section'
    | '/verify/$id'
    | '/admin/'
    | '/courses/'
    | '/instructor/'
    | '/verify/'
    | '/assignments/$courseId/$assignmentId'
    | '/quizzes/$courseId/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RestrictedRoute: typeof RestrictedRoute
  AdminSectionRoute: typeof AdminSectionRoute
  InstructorSectionRoute: typeof InstructorSectionRoute
  LearnCourseIdRoute: typeof LearnCourseIdRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  RestPasswordTokenRoute: typeof RestPasswordTokenRoute
  StudentSectionRoute: typeof StudentSectionRoute
  VerifyIdRoute: typeof VerifyIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  InstructorIndexRoute: typeof InstructorIndexRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
  AssignmentsCourseIdAssignmentIdRoute: typeof AssignmentsCourseIdAssignmentIdRoute
  QuizzesCourseIdQuizIdRoute: typeof QuizzesCourseIdQuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restricted': {
      id: '/restricted'
      path: '/restricted'
      fullPath: '/restricted'
      preLoaderRoute: typeof RestrictedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/admin/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/instructor/': {
      id: '/instructor/'
      path: '/instructor'
      fullPath: '/instructor/'
      preLoaderRoute: typeof InstructorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/$section': {
      id: '/instructor/$section'
      path: '/instructor/$section'
      fullPath: '/instructor/$section'
      preLoaderRoute: typeof InstructorSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$courseId': {
      id: '/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof LearnCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rest-password/$token': {
      id: '/rest-password/$token'
      path: '/rest-password/$token'
      fullPath: '/rest-password/$token'
      preLoaderRoute: typeof RestPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/$section': {
      id: '/student/$section'
      path: '/student/$section'
      fullPath: '/student/$section'
      preLoaderRoute: typeof StudentSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/$courseId/$assignmentId': {
      id: '/assignments/$courseId/$assignmentId'
      path: '/assignments/$courseId/$assignmentId'
      fullPath: '/assignments/$courseId/$assignmentId'
      preLoaderRoute: typeof AssignmentsCourseIdAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$courseId/$quizId': {
      id: '/quizzes/$courseId/$quizId'
      path: '/quizzes/$courseId/$quizId'
      fullPath: '/quizzes/$courseId/$quizId'
      preLoaderRoute: typeof QuizzesCourseIdQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RestrictedRoute: RestrictedRoute,
  AdminSectionRoute: AdminSectionRoute,
  InstructorSectionRoute: InstructorSectionRoute,
  LearnCourseIdRoute: LearnCourseIdRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  RestPasswordTokenRoute: RestPasswordTokenRoute,
  StudentSectionRoute: StudentSectionRoute,
  VerifyIdRoute: VerifyIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  InstructorIndexRoute: InstructorIndexRoute,
  VerifyIndexRoute: VerifyIndexRoute,
  AssignmentsCourseIdAssignmentIdRoute: AssignmentsCourseIdAssignmentIdRoute,
  QuizzesCourseIdQuizIdRoute: QuizzesCourseIdQuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
